variables:
  # relative namespace of project
  REL_NAMESPACE: "/structure/python/"

release:
  image: python:latest
  before_script:
      - pip install anybadge
  stage: build
  script:
    # create badges (use version from python compiled spec)
    - git fetch --tags
    - version_str=$(git describe --tags $(git rev-list --tags --max-count=1))
    - version_var=$(echo $version_str | grep -E 'v[0-9].[0-9].[0-9]' | tail -n 1 | cut -c2-)
    - echo "Version for badges $version_var"
    - anybadge -l version --value="${version_var::-1}" --file=version.svg --color=green
    # create folder public for badges
    - mkdir -p "public/${REL_NAMESPACE}"
    - cp *.svg "public/${REL_NAMESPACE}"
  artifacts:
    name: pages
    paths:
    - public
  only:
  - master

rsync:
  stage: deploy
  image: registry.gitlab.vgiscience.org/lbsn/lbsn.vgiscience.org/rsync-ssh:latest
  before_script:
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVKEY}" | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
  - ssh "${STAGING_SERVER}" mkdir -p "${STAGING_PATH}${REL_NAMESPACE}"
  - rsync -avu -zz --no-perms --omit-dir-times --del --chown=www-data:www-data --chmod=D775,F664 "public/${REL_NAMESPACE}" "${STAGING_SERVER}:${STAGING_PATH}${REL_NAMESPACE}"
  only:
  - master

